---
- hosts: all
  become: yes

  tasks:
    - name: Install Remi repo
      yum:
        name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        state: present

    - name: Import Remi GPG key
      rpm_key:
        key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
        state: present

    - name: Install EPEL repo
      yum: name=epel-release state=present

    - name: Ensure firewalld is stopped (since this is for testing)
      service: name=firewalld state=stopped

    - name: Install Node.js and npm
      yum: name=npm state=present enablerepo=epel

    - name: Install Forever (to run our node.js app)
      npm: name=forever global=yes state=present

    - name: Ensure node.js app folder exists
      file: "path={{ node_apps_location }} state=directory"

    - name: Copy example node.js app to server
      copy: "src=hello-world dest={{ node_apps_location }}"

    - name: Install app dependencies defined in package.json
      npm: path={{ node_apps_location }}/hello-world

    - name: Check list of running node.js apps
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start example node.js app
      command: "forever start {{ node_apps_location }}/hello-world/app.js"
      when: "forever_list.stdout.find(node_apps_location + '/hello-world/app.js') == -1"